# Generated by Django 2.2.4 on 2020-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201223_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
